version: "3.3"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres-mates
    shm_size: '1gb'
    ports:
      - 5436:5432
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      API_POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      API_POSTGRES_HOST: postgres
      API_POSTGRES_PORT: "5436"
      API_POSTGRES_DB: mates-db
  redis:
    image: redis
    container_name: redis-mates
    ports:
      - 6379:6379
